const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const quick=[['☼','Clima','Previsão do tempo','weather'],['W','Wikipedia','Pesquisar fatos','wiki'],['▶','YouTube','Vídeos e músicas','youtube'],['G','Google','Pesquisar na web','search'],['a','Amazon','Compras e ofertas','amazon'],['▣','Notícias','Últimas notícias','news'],['☻','Piadas','Uma boa risada','joke'],['◇','Dicionário','Tradução e significados','dictionary'],['◎','Câmera','Tirar fotos/vídeos','camera'],['▣','Captura de tela','Imagem da tela','screenshot'],['♫','Música','Reproduzir músicas','music'],['✉','E-mail','Enviar e receber','email'],['◆','Memória','Lembrar de algo','memory'],['⌁','OCR','Ler textos da tela','ocr'],['⚙','Sistema','Informações do PC','system']];
$('#quickGrid').innerHTML=quick.map(x=>`<button class="quick-card" data-action="${x[3]}"><span class="ico">${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></button>`).join('');
function speak(text){if(!('speechSynthesis'in window))return; speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='pt-BR';u.rate=.98;u.pitch=1; speechSynthesis.speak(u)}
function reply(title,text,voice=text){$('#responseTitle').textContent=title;$('#response').textContent=text;$('#voiceStatus').textContent=text; speak(voice)}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2400)}
function openModal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')}
$('#close').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')};
function doSearch(){const q=prompt('O que você quer pesquisar?');if(q){reply('Pesquisa iniciada',`Abrindo resultados para “${q}”`);window.open('https://www.google.com/search?q='+encodeURIComponent(q),'_blank')}}
async function weather(){try{const pos=await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,{timeout:5000}));const {latitude,longitude}=pos.coords;const r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=temperature_2m,weather_code&daily=temperature_2m_max&timezone=auto`);const d=await r.json();$('#temp').textContent=Math.round(d.current.temperature_2m)+'°C';$('#desc').textContent=weatherText(d.current.weather_code);$('#f1').textContent=Math.round(d.daily.temperature_2m_max[0])+'°';$('#f2').textContent=Math.round(d.daily.temperature_2m_max[1])+'°';$('#f3').textContent=Math.round(d.daily.temperature_2m_max[2])+'°';$('#f4').textContent=Math.round(d.daily.temperature_2m_max[3])+'°';$('#weatherPlace').textContent='LOCAL';reply('Clima atualizado',`Agora está ${Math.round(d.current.temperature_2m)} graus. ${weatherText(d.current.weather_code)}.`)}catch(e){$('#desc').textContent='Permita a localização para obter o clima';reply('Clima','Não consegui acessar sua localização.')}}
function weatherText(c){if(c===0)return'céu limpo';if(c<=3)return'poucas nuvens';if(c<=48)return'neblina';if(c<=67)return'chuvoso';if(c<=77)return'neve';if(c<=82)return'chuva';return'tempestade'}
async function wiki(){const q=prompt('O que você quer pesquisar na Wikipedia?');if(!q)return;try{const r=await fetch('https://pt.wikipedia.org/api/rest_v1/page/summary/'+encodeURIComponent(q));const d=await r.json();const text=d.extract||'Não encontrei um resumo.';openModal('WIKIPEDIA',`<h2>${d.title||q}</h2><p>${text}</p><button class="action" onclick="window.open('${d.content_urls?.desktop?.page||'https://pt.wikipedia.org'}','_blank')">Abrir página</button>`);reply('Wikipedia',text.slice(0,160));}catch(e){reply('Wikipedia','Não consegui consultar agora.')}}
function youtube(){const q=prompt('O que você quer pesquisar no YouTube?');if(q)window.open('https://www.youtube.com/results?search_query='+encodeURIComponent(q),'_blank')}
function amazon(){window.open('https://www.amazon.com.br/','_blank')}
async function news(){openModal('ÚLTIMAS NOTÍCIAS','<p>Para manter o site sem servidor e sem instalação, a seção usa uma busca web segura. Escolha uma categoria:</p><button class="action" onclick="window.open(\'https://news.google.com/?hl=pt-BR&gl=BR&ceid=BR:pt-419\',\'_blank\')">Abrir Google Notícias</button>');reply('Notícias','Abrindo as últimas notícias.')}
function joke(){const jokes=['Por que o computador foi ao médico? Porque estava com um vírus.','O que o Wi-Fi disse para o celular? Você é meu tipo de conexão.','Meu processador pediu férias. Disse que precisava de um reboot.'];const j=jokes[Math.floor(Math.random()*jokes.length)];openModal('PIADA',`<p style="font-size:18px">${j}</p>`);reply('Piada',j)}
function dictionary(){const q=prompt('Qual palavra você quer consultar?');if(q)window.open('https://dicionario.priberam.org/'+encodeURIComponent(q),'_blank')}
function memory(){const old=localStorage.getItem('jarvis_memory')||'';openModal('MEMÓRIA',`<p>${old?`Memória atual: <b>${escapeHtml(old)}</b>`:'Nenhuma memória salva.'}</p><input id="memoryInput" placeholder="Digite algo para eu lembrar"><button class="action" id="saveMemory">Salvar memória</button><button class="action" id="clearMemory">Apagar</button>`);$('#saveMemory').onclick=()=>{const v=$('#memoryInput').value.trim();if(v){localStorage.setItem('jarvis_memory',v);toast('Memória salva');$('#modal').classList.add('hidden');reply('Memória salva','Vou lembrar disso neste navegador.')}};$('#clearMemory').onclick=()=>{localStorage.removeItem('jarvis_memory');toast('Memória apagada');$('#modal').classList.add('hidden')}}
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function camera(){try{openModal('CÂMERA','<video class="camera-video" id="cam" autoplay playsinline></video><button class="action" id="snap">Tirar foto</button>');const stream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});$('#cam').srcObject=stream;$('#snap').onclick=()=>{const v=$('#cam'),c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);const a=document.createElement('a');a.download='jarvis-photo.png';a.href=c.toDataURL('image/png');a.click();reply('Foto capturada','A imagem foi salva.')}}catch(e){reply('Câmera','Não foi possível acessar a câmera. Verifique a permissão do navegador.')}}
async function screenshot(){try{if(!navigator.mediaDevices?.getDisplayMedia)throw 0;const stream=await navigator.mediaDevices.getDisplayMedia({video:true});const v=document.createElement('video');v.srcObject=stream;await v.play();await new Promise(r=>setTimeout(r,300));const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);stream.getTracks().forEach(t=>t.stop());const a=document.createElement('a');a.download='jarvis-screenshot.png';a.href=c.toDataURL('image/png');a.click();reply('Captura concluída','A captura de tela foi salva.')}catch(e){reply('Captura de tela','O navegador cancelou ou não oferece captura de tela.')}}
function system(){const nav=navigator;$('#os').textContent=nav.platform||'Navegador';$('#cpu').textContent=(nav.hardwareConcurrency||'--')+' núcleos';$('#ram').textContent=(nav.deviceMemory?nav.deviceMemory+' GB':'indisponível');openModal('SISTEMA',`<div class="sysrow"><span>Plataforma</span><b>${escapeHtml(nav.platform)}</b></div><div class="sysrow"><span>Navegador</span><b>${escapeHtml(nav.userAgent.split(' ').slice(-1)[0])}</b></div><div class="sysrow"><span>Núcleos</span><b>${nav.hardwareConcurrency||'--'}</b></div><div class="sysrow"><span>Memória estimada</span><b>${nav.deviceMemory?nav.deviceMemory+' GB':'Não exposta'}</b></div>`);reply('Sistema','Mostrando as informações disponíveis pelo navegador.')}
function music(){const q=prompt('O que você quer ouvir?');if(q)window.open('https://www.youtube.com/results?search_query='+encodeURIComponent(q+' música'),'_blank')}
function email(){openModal('E-MAIL','<p>O navegador não pode enviar e-mail diretamente sem um servidor. Posso abrir seu cliente de e-mail.</p><input id="emailTo" placeholder="destinatario@email.com"><input id="emailSub" placeholder="Assunto" style="margin-top:8px"><button class="action" id="emailOpen">Abrir e-mail</button>');$('#emailOpen').onclick=()=>{const to=$('#emailTo').value,sub=$('#emailSub').value;window.location.href=`mailto:${encodeURIComponent(to)}?subject=${encodeURIComponent(sub)}`}}
function ocr(){openModal('OCR','<p>O navegador não precisa de Tesseract instalado. Envie uma imagem com texto para usar OCR local.</p><input id="ocrFile" type="file" accept="image/*"><div id="ocrResult"></div>');$('#ocrFile').onchange=()=>$('#ocrResult').innerHTML='<p>OCR web pode ser conectado aqui usando uma biblioteca hospedada. A versão atual mantém a interface sem instalar nada.</p>'}
function handle(action){({listen:startListening,weather,wiki,search:doSearch,youtube,amazon,news,joke,dictionary,memory,screenshot,camera,music,email,system,ocr}[action]||(()=>{}))()}
$$('[data-action]').forEach(b=>b.onclick=()=>handle(b.dataset.action));$('#send').onclick=()=>command($('#command').value);$('#command').addEventListener('keydown',e=>{if(e.key==='Enter')command(e.target.value)});$('#commandMic').onclick=()=>startListening();$('#mic').onclick=()=>startListening();
function command(q){q=(q||'').trim();if(!q)return;$('#command').value='';const l=q.toLowerCase();if(l.includes('wikipedia'))return wiki();if(l.includes('youtube'))return youtube();if(l.includes('amazon'))return amazon();if(l.includes('clima')||l.includes('tempo'))return weather();if(l.includes('notícia'))return news();if(l.includes('piada'))return joke();if(l.includes('dicionário'))return dictionary();if(l.includes('memória')||l.includes('lembre'))return memory();if(l.includes('câmera'))return camera();if(l.includes('captura')||l.includes('screenshot'))return screenshot();if(l.includes('música')||l.includes('musica'))return music();if(l.includes('email')||l.includes('e-mail'))return email();if(l.includes('sistema')||l.includes('cpu'))return system();if(l.includes('pesquis')||l.startsWith('search'))return doSearch();if(l.includes('hora')||l.includes('tempo')){const t=new Date().toLocaleTimeString('pt-BR');return reply('Horário atual',`Agora são ${t}.`)}if(l.includes('quem é você')||l.includes('seu nome'))return reply('J.A.R.V.I.S','Meu nome é J.A.R.V.I.S, seu assistente pessoal.');if(l.includes('está aí')||l.includes('are you there'))return reply('J.A.R.V.I.S','Sim. Estou online e pronto para ajudar.');if(l.includes('lembra'))return reply('Memória',localStorage.getItem('jarvis_memory')||'Não tenho nenhuma memória salva.');reply('Comando recebido',`Entendi: “${q}”.`)}
let recognition;function startListening(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('Reconhecimento de voz não disponível neste navegador');return}if(recognition){try{recognition.stop()}catch(e){}}recognition=new SR();recognition.lang='pt-BR';recognition.interimResults=false;recognition.maxAlternatives=1;$('#mic').classList.add('listening');$('#coreState').textContent='LISTENING';$('#voiceStatus').textContent='Ouvindo...';recognition.onresult=e=>command(e.results[0][0].transcript);recognition.onerror=()=>reply('Microfone','Não consegui entender. Tente novamente.');recognition.onend=()=>{$('#mic').classList.remove('listening');$('#coreState').textContent='ONLINE';$('#voiceStatus').textContent='Aguardando comando...'};recognition.start()}
function tick(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString('pt-BR');$('#date').textContent=d.toLocaleDateString('pt-BR');const usage=20+Math.floor(Math.random()*35);$('#usage').textContent=usage+'%';$('#meterBar').style.width=usage+'%';$('#latency').textContent=(.1+Math.random()*.3).toFixed(1)+'s'}setInterval(tick,1000);tick();weather();
