const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const say=(text)=>{ $('#reply').textContent=text; $('#statusText').textContent='Executando comando...'; speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text); u.lang='pt-BR';u.rate=.95;speechSynthesis.speak(u); setTimeout(()=>$('#statusText').textContent='Pronto para ajudar.',800)};
function openModal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=`<div class="modal-content">${html}</div>`;$('#modal').classList.remove('hidden')}
$('#close').onclick=()=>$('#modal').classList.add('hidden'); $('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')};
function open(url){window.open(url,'_blank','noopener,noreferrer')}
function cmdSearch(q){if(!q) q=prompt('O que deseja pesquisar?'); if(q){say('Abrindo a pesquisa.');open('https://www.google.com/search?q='+encodeURIComponent(q))}}
async function weather(){try{let pos=await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,{timeout:6000}));let {latitude:lat,longitude:lon}=pos.coords;let g=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=Poços%20de%20Caldas&count=1&language=pt&format=json`).then(r=>r.json());if(g.results?.[0]){lat=g.results[0].latitude;lon=g.results[0].longitude;$('#place').textContent='Poços de Caldas — MG'}let d=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,weather_code,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,weather_code&timezone=auto&forecast_days=4`).then(r=>r.json());$('#temp').textContent=Math.round(d.current.temperature_2m)+'°C';$('#weatherIcon').textContent=icon(d.current.weather_code);$('#forecast').innerHTML=d.daily.time.map((t,i)=>`<div>${new Date(t).toLocaleDateString('pt-BR',{weekday:'short'}).replace('.','')}<b>${icon(d.daily.weather_code[i])}</b>${Math.round(d.daily.temperature_2m_max[i])}° / ${Math.round(d.daily.temperature_2m_min[i])}°</div>`).join('');say(`A temperatura atual é ${Math.round(d.current.temperature_2m)} graus.`)}catch(e){$('#place').textContent='Permissão de localização necessária';say('Não consegui acessar sua localização.')} }
function icon(c){return c===0?'☀':c<4?'⛅':c<60?'☁':'🌧'}
async function wiki(){let q=prompt('O que você quer pesquisar na Wikipedia?');if(!q)return;try{let d=await fetch('https://pt.wikipedia.org/api/rest_v1/page/summary/'+encodeURIComponent(q)).then(r=>r.json());openModal('WIKIPEDIA',`<h2>${d.title||q}</h2><p>${d.extract||'Nenhum resumo encontrado.'}</p><button class="action-btn" onclick="open('https://pt.wikipedia.org/wiki/${encodeURIComponent(q)}')">ABRIR WIKIPEDIA</button>`);say('Encontrei informações na Wikipedia.')}catch(e){say('Não consegui consultar a Wikipedia agora.')}}
async function dictionary(){let q=prompt('Qual palavra?');if(!q)return;try{let d=await fetch('https://api.dictionaryapi.dev/api/v2/entries/en/'+encodeURIComponent(q)).then(r=>r.json());let m=d[0]?.meanings?.[0];openModal('DICIONÁRIO',`<h2>${q}</h2><p>${m?.partOfSpeech||''}</p><p>${m?.definitions?.[0]?.definition||'Definição não encontrada.'}</p>`);say('Aqui está a definição.')}catch(e){say('Não encontrei essa palavra no dicionário.')}}
function joke(){const a=['Por que o computador foi ao médico? Porque estava com um vírus.','O que o Wi-Fi disse para o computador? Você é minha conexão.','Por que o programador terminou o namoro? Porque não tinha mais espaço para a relação.'];say(a[Math.floor(Math.random()*a.length)])}
function memory(){let m=localStorage.getItem('jarvisMemory')||'';openModal('MEMÓRIA',`<p>Memória local deste navegador.</p><textarea id="memoryText" rows="5">${m.replace(/</g,'&lt;')}</textarea><button class="action-btn" id="saveMem">SALVAR</button> <button class="action-btn" id="clearMem">APAGAR</button>`);$('#saveMem').onclick=()=>{localStorage.setItem('jarvisMemory',$('#memoryText').value);updateMemory();say('Memória atualizada.');};$('#clearMem').onclick=()=>{localStorage.removeItem('jarvisMemory');$('#memoryText').value='';updateMemory();say('Memória apagada.')}}
function updateMemory(){$('#memStatus').textContent=(localStorage.getItem('jarvisMemory')||'').length?'1 item':'0 itens'}
function camera(){openModal('CÂMERA',`<video id="cam" autoplay playsinline style="width:100%;border:1px solid var(--line)"></video><button class="action-btn" id="stopCam">FECHAR CÂMERA</button>`);navigator.mediaDevices?.getUserMedia({video:true}).then(s=>{$('#cam').srcObject=s;$('#stopCam').onclick=()=>{s.getTracks().forEach(t=>t.stop());$('#modal').classList.add('hidden')}}).catch(()=>say('O navegador bloqueou o acesso à câmera.'))}
async function screenshot(){try{const stream=await navigator.mediaDevices.getDisplayMedia({video:true});const v=document.createElement('video');v.srcObject=stream;await v.play();await new Promise(r=>setTimeout(r,300));const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);stream.getTracks().forEach(t=>t.stop());const a=document.createElement('a');a.href=c.toDataURL('image/png');a.download='jarvis-screenshot.png';a.click();say('Captura de tela salva.')}catch(e){say('A captura foi cancelada.')}}
function action(a){switch(a){case'weather':return weather();case'wiki':return wiki();case'search':return cmdSearch();case'youtube':{let q=prompt('O que quer procurar no YouTube?');if(q)open('https://www.youtube.com/results?search_query='+encodeURIComponent(q));return}case'amazon':return open('https://www.amazon.com.br');case'news':return news();case'joke':return joke();case'dictionary':return dictionary();case'memory':return memory();case'camera':return camera();case'screenshot':return screenshot();case'ocr':return openModal('OCR',`<p>O navegador não possui OCR nativo universal. Você pode abrir uma imagem e usar um serviço OCR externo sem instalar nada.</p><button class="action-btn" onclick="open('https://www.google.com/search?q=OCR+online')">ABRIR OCR ONLINE</button>`);case'music':{let q=prompt('Qual música?');if(q)open('https://www.youtube.com/results?search_query='+encodeURIComponent(q+' música'));return}case'email':return open('mailto:?subject=Mensagem%20J.A.R.V.I.S&body=Olá!');case'system':return system();case'voice':return listen();}}
async function news(){try{let d=await fetch('https://api.spaceflightnewsapi.net/v4/articles/?limit=5').then(r=>r.json());$('#newsList').innerHTML=d.results.map(x=>`<div class="news-item"><b>${x.title}</b><span>${new Date(x.published_at).toLocaleString('pt-BR')}</span></div>`).join('');say('Atualizei as notícias.')}catch(e){$('#newsList').innerHTML='<div class="news-item">Não foi possível carregar notícias agora.</div>';say('Não consegui atualizar as notícias.')}}
function system(){openModal('SISTEMA',`<p><b>Navegador:</b> ${navigator.userAgent}</p><p><b>Plataforma:</b> ${navigator.platform}</p><p><b>Idioma:</b> ${navigator.language}</p><p><b>Tela:</b> ${screen.width} × ${screen.height}</p><p><b>Online:</b> ${navigator.onLine?'Sim':'Não'}</p>`);say('Informações do sistema exibidas.');}
let recognition;function listen(){if(!('SpeechRecognition'in window||'webkitSpeechRecognition'in window)){say('Reconhecimento de voz não é suportado neste navegador.');return}const R=window.SpeechRecognition||window.webkitSpeechRecognition;recognition=new R();recognition.lang='pt-BR';recognition.interimResults=false;recognition.onstart=()=>{$('#coreState').textContent='OUVINDO';$('#statusText').textContent='Aguardando comando...';$('#mic').textContent='◉'};recognition.onend=()=>{$('#coreState').textContent='ONLINE';$('#mic').textContent='🎙'};recognition.onerror=()=>say('Não consegui entender o comando.');recognition.onresult=e=>{$('#command').value=e.results[0][0].transcript;execute(e.results[0][0].transcript)};recognition.start()}
function execute(q){q=q.toLowerCase().trim();if(!q)return;if(q.includes('clima')||q.includes('tempo'))return weather();if(q.includes('wikipedia'))return wiki();if(q.includes('youtube')){let x=q.replace('youtube','').replace('pesquisar','').trim();return x?open('https://www.youtube.com/results?search_query='+encodeURIComponent(x)):action('youtube')}if(q.includes('amazon'))return action('amazon');if(q.includes('piada'))return joke();if(q.includes('dicionário'))return dictionary();if(q.includes('captura')||q.includes('screenshot'))return screenshot();if(q.includes('câmera'))return camera();if(q.includes('notícias'))return news();if(q.includes('memória')||q.includes('lembrar'))return memory();if(q.includes('google')||q.includes('pesquisar')||q.includes('buscar'))return cmdSearch(q.replace(/google|pesquisar|buscar/g,'').trim());if(q.includes('hora')){say('Agora são '+new Date().toLocaleTimeString('pt-BR'));return}if(q.includes('quem é você')||q.includes('seu nome')){say('Meu nome é J.A.R.V.I.S. Just A Rather Very Intelligent System.');return}if(q.includes('está aí')||q.includes('esta ai')){say('Sim, senhor. A seu serviço.');return}if(q.includes('olá')||q.includes('ola')){say('Olá. Sistemas online e prontos.');return}say('Comando recebido. Ainda estou aprendendo essa função. Tente clima, Wikipedia, YouTube, pesquisar, notícias, piada ou memória.')}
$('#send').onclick=()=>execute($('#command').value);$('#command').addEventListener('keydown',e=>{if(e.key==='Enter')execute($('#command').value)});$('#mic').onclick=listen;$$('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));$('#newsBtn').onclick=news;$('#settingsBtn').onclick=()=>openModal('CONFIGURAÇÕES','<p>J.A.R.V.I.S Web Core — sem instalação.</p><p>Voz: navegador<br>Memória: localStorage<br>Clima: Open-Meteo<br>Wikipedia: API pública</p>');
function clock(){let d=new Date();$('#clock').textContent=d.toLocaleTimeString('pt-BR');$('#date').textContent=d.toLocaleDateString('pt-BR');}setInterval(clock,1000);clock();updateMemory();$('#browser').textContent=navigator.userAgent.includes('Chrome')?'Chrome':navigator.userAgent.includes('Firefox')?'Firefox':navigator.userAgent.includes('Safari')?'Safari':'Web';$('#platform').textContent=navigator.platform;$('#lang').textContent=navigator.language;weather();news();
